### ISSUE TITLE
Ingest NTW and Say Brother PBCore

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1215]
**Done When**
PBCore xml from #1213 and #1214 has been successfully ingested in Open Vault and has been checked.

**Comment by Muraszko** [comment]
@afred @mccalluc 
Here's links to the server for the XML to upload into Open Vault.
There are two sets of XML, one for new records created by Sadie with generated UUIDs and and a second set of xml that Sadie has created from existing Open Vault XML.

Update existing Open Vault records with this XML:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/xml/updated_xml_for_programs

Create new records with this set of newly created XML:
smb://deptfs.wgbh.org/dept/MLA/Mellon/Phase III/Say_Brother_NTW/xml/new_xml_for_clips

**Comment by afred** [comment]
@Muraszko the filenames under the `updated_xml_for_programs` dir do not match existing filenames. Are they supposed to be the same as existing files?

**Comment by afred** [comment]
^^ it looks like that is the case, right? They need to be named the same thing in order to be tracked by git properly. Do you have a quick way to rename the files according to the convention being used in Stash currently? It follows a naming scheme like `P_03WI3YC0RFHGV6K_pbcore.xml`.. so in other words all files that are named something like this: `openvault_5712.pbcore.xml` will have to be named something like this instead `P_03WI3YC0RFHGV6K_pbcore.xml`. I can do this in ruby. Will probably take ~ 20 min or so to get it right.

**Comment by Muraszko** [comment]
Yes please, thanks.

**Comment by afred** [comment]
These updates remove the default namespace for PBCore. For instance, for file with MARS ID="PROG_0C8NCD3KQ35PA52"...

```diff
 <?xml version="1.0"?>
-<pbcoreDescriptionDocument xmlns="http://www.pbcore.org/PBCore/PBCoreNamespace.html" schemaVersion="2.0">
+<pbcoreDescriptionDocument schemaVersion="2.0">
   <pbcoreIdentifier source="MARS PROGRAM Record ID">PROG_0C8NCD3KQ35PA52</pbcoreIdentifier>
   <pbcoreTitle titleType="Series">New Television</pbcoreTitle>
   <pbcoreTitle titleType="Program">Lown Ranjer Aind Tontow, The</pbcoreTitle>
```

@mccalluc we want to keep that, yes?

**Comment by mccalluc** [comment]
@afred: Safer to keep it, yes. Downstream machinery may or may not be depending on it, but no need to introduce another variable.

**Comment by afred** [comment]
blerg.. @Muraszko @sroosa it looks like the ingester couldn't identify the type of assets for the newly created records. So none of those got ingested on a first pass (the updated records appear to have succeeded).

Either we need to make the new metadata as recognizable as the existing metadata, or we need to adjust the ingester to identify the new metadata.

**Comment by afred** [comment]
Here is a list of the files that didn't make it in yet: https://gist.github.com/afred/02e975484531b39de553

and here is a list of their UUIDs if that helps: https://gist.github.com/afred/e2d237fa09750f937fbc

**Comment by afred** [comment]
I think this is due to using the value "Clip" in `pbcoreAssetType`. This makes logical sense.. but the ingester hasn't had to deal with it yet.

I would love to make it a policy of Openvault (and ideally all of MLA) that all pbcore documents have an asset type. If we had this from the start it would have saved so much time. Plus it just makes sense.

**Comment by afred** [comment]
done
